services:
  backend:
    build:
      context: ./buzzaar-backend/
      dockerfile: Dockerfile
    command: sh -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./buzzaar-backend/buzzaar_core:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=True
      - PATH=/root/.local/bin:$PATH
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./buzzaar-frontend/
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./buzzaar-frontend/buzzaar-ui:/app
      - /app/node_modules
    ports:
      - "4200:4200" 
    command: npm start
    environment:
      - NODE_ENV=development

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

