# Generated by Django 5.1.1 on 2024-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default='Undefined', max_length=22),
            preserve_default=False,
        ),
    ]
