name: Backend Test Cases
on:
  push:
    paths:
      - 'buzzaar-backend/**'
    branches:
      - main
      - dev
  pull_request:
    paths:
      - 'buzzaar-backend/**'
    branches:
      - main
      - dev
  workflow_dispatch: {}

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd="pg_isready -h localhost -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Django dependencies
      working-directory: ./buzzaar-backend/buzzaar_core
      run: |
        python -m venv venv
        ./venv/bin/pip install --upgrade pip setuptools
        ./venv/bin/pip install poetry
        ./venv/bin/poetry lock --no-update
        ./venv/bin/poetry install

    - name: Set environment variables
      run: |
        echo "POSTGRES_DB=test_db" >> $GITHUB_ENV
        echo "POSTGRES_USER=test_user" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=test_password" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> $GITHUB_ENV
        echo "DATABASE_HOST=localhost" >> $GITHUB_ENV
        echo "DATABASE_PORT=5432" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p ${{ env.DATABASE_PORT }} -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }}; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done

    - name: Run migrations
      working-directory: ./buzzaar-backend/buzzaar_core/
      run: |
        ./venv/bin/poetry run python manage.py migrate

    - name: Run pytest tests
      working-directory: ./buzzaar-backend/buzzaar_core/
      run: |
        ./venv/bin/poetry run pytest

